travis:
  secure:
    BINSTAR_TOKEN: f1qqFuxd9i1UlWsK31Cxkz5oeQvMRBjLDbzNwuaukDBCPvRFr20kJg+7QpbPTpk6RE3EmbaE3QQC+Xzms5dHErjCSZN9YIIODNcCKvrkLcT8+NejR8dirWqmXa7ahVI0y2/9mvpduRyHhhqPajShv12lb93vEc+uViRMfk+EjHqnJBqgT0uIr1DfwIM/ozXeDhQxJDSqj4fr+kya8YXr1gv8WA6RK5vBw/jZXGjlm7MGb7AKO2c9CwRhg6IyT3H9SIiwQfA+jk9yE2Ts0UgNHRlS9ZEFisU6BRJxuqmYk/L3rQKsLGGo2+eyawPqlaPkR8EY+yzM5PlZfppIKFyY4TagryG/zCHa907zZYFXhdnYqOTfNleiYqqO5FS/9Bti6EXUy8xREJ6HyQ/ZCMtG4jm+PUxTjxCQ7/imhIEwtcGcTN0yLwfrIHOikT2zXayskd+JGHNBxK5Lq7SoGZw1iEylb4pbUl8y5B75usfMMZEfJi5J+zSK3hbvq/0oHIpj4XrLA7UnzgOQmEM0IV9s2YVpil9vrfTnhWVT+6nnhQ1aSaFcQFYD153imIpVhBlwdB4XgZvFS9mjAfz566U3br2Kij4m1Pvd1lh9hCnsip3mOyc9ikPAiOJZ9HtVp+r0vfYRGHGPf5YAGZJkPrAYYzhMHf43VMXxwspfVEaAlyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
